apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service
spec:
  selector:
    matchLabels:
      app: statistics-service
  replicas: 1
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
        - name: statistics-service
          image: venenium/statisticsservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: statistics-service
spec:
  type: NodePort
  selector:
    app: statistics-service
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
