apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  type: LoadBalanced
  rules:
    - http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /investments/?(.*)
            pathType: Prefix
            backend:
              service:
                name: investment-service-svc
                port:
                  number: 9001
